// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDoHBxKazoPYeGWWltE8GRzshbVHC1lU',
    appId: '1:370459725438:web:8d995490c0d72daedf522f',
    messagingSenderId: '370459725438',
    projectId: 'fir-todo-39421',
    authDomain: 'fir-todo-39421.firebaseapp.com',
    storageBucket: 'fir-todo-39421.appspot.com',
    measurementId: 'G-D3RNE8L9VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvN_xb1RgDt7yfOSLHRJapZ-Ku8vTY4rk',
    appId: '1:370459725438:android:a70d36466f12f19ddf522f',
    messagingSenderId: '370459725438',
    projectId: 'fir-todo-39421',
    storageBucket: 'fir-todo-39421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_K7_A6iACWtRAB8ktTcHKDqjNdkSSAe8',
    appId: '1:370459725438:ios:3ee38831fb5c45b3df522f',
    messagingSenderId: '370459725438',
    projectId: 'fir-todo-39421',
    storageBucket: 'fir-todo-39421.appspot.com',
    iosClientId: '370459725438-d027hb8ohk1458ocrgl0r6lrn93utcgr.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.firebaseNoteTwo',
  );
}
